### ISSUE TITLE
Figure out better tests than "does it pass linting"

### ISSUE THREAD

**Issue by joshualyon7** [ud-cis-discord/Sage#124]

**Comment by joshualyon7** [comment]
This might wait until Sage is refactored into classes.

**Comment by BenSegal855** [comment]
The system described below is a theoretical system to provide end to end testing.
# S.T.O.V.E System
The Sage Testing, Observation, and Verification Environment (Stove) system is a second bot account designed to interact with Sage in order to test and verify commands and pieces. This comment describes my early thoughts on how such a system would work. As such, there should be more panning and thought put into a system like this before coding begins.
### Stove's main entry point
Stove will need a token stored in the config and should log on as a bot just like Sage. Once the `onReady` event occurs, Stove should begin testing Sage. In my imagination Sage and Stove are started as separate processes running at the same time, both created by an external source (like an npm script).
### Testing mode
Testing mode would be enabled with a cli argument and would set a boolean in Sage's client to `true`. This would allow for pieces such as the command handler to listen to messages from Stove when they otherwise would be ignored. For this to work properly, Stove's client ID should be stored in the config to make sure that Stove is the only Bot user that Sage will be interacting with. Sage should also create a new database upon startup in testing mode with a unique name. This is to ensure no test data enters the production database and no test results are affected by data that was already in an existing testing database.
### Testing Pieces
Currently, each piece exports one register function. With Stove, each piece would also export a testing function. This function will be given the Stove client just like how the register function is given the Sage client. The function is then responsible for using Stove to interact with Sage by sending messages, creating roles etc. The function should also be listening for any messages or actions taken by Sage to check that Sage is preforming correctly. At the end of the test, the function should clean up any roles, channels etc. that it created.
### Testing commands
The testing of commands is taken care of by the command handlers test function. Similar to the command handlers register function, it will look at all commands for a `test` property. This property can either be a [`CommandTest`](#the-commandtest-object) object, an array of `CommanTest` objects or a function that takes the client as an argument. If the `test` property is a `CommandTest` or an array of  `CommandTest`s, each `testStr` is sent in a channel and then Stove uses a [message collector](https://discord.js.org/#/docs/main/stable/class/MessageCollector) to wait for Sage's response. The response is then compared to the `result` property and if the message content matches the result, the test passes. If a function is given as the `test` property, the function is ran. It is expected that the function will test the command in question and return true if the command passed all tests and will throw an error or return false if a test failed.

#### The CommandTest object
```ts
interface CommandTest {
    testStr: string;
    result: string | MessageEmbed;
}
```

**Comment by joshualyon7** [comment]
Does this design die with interactions? I don't know if a bot can create interactions

**Comment by sbrugel** [comment]
> I don't know if a bot can create interactions

They cannot
